library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
MotorSCC <- SCC[which(SCC$SCC.Level.One=="Mobile Sources"),]$SCC
both <- intersect(NEI$SCC, MotorSCC)
SubBalti <- subset(NEI, fips == "24510" & SCC %in% both)
SubLA <- subset(NEI, fips == "06037" & SCC %in% both)
BaltiEmi<-with(SubBalti, tapply(Emissions, year, mean, na.rm = T))
LAEmi<-with(SubLA, tapply(Emissions, year, mean, na.rm =T))
dBalti<-data.frame(years = names(BaltiEmi), mean = BaltiEmi)
dLA<-data.frame(years = names(LAEmi), mean = LAEmi)
mrg <- merge(dBalti, dLA, by = "years")
with(mrg, plot( mrg[,2],names(mrg[,2]), xlim =c( -1, 100), col = "blue"))
with(mrg, points( mrg[,3], names(mrg[,3]), col = "red"))
dev.copy(png, file ="Plot6.png")
dev.off()