library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
NEI <- transform(NEI, year= factor(year))
NEI <- transform(NEI, type= factor(type))
SubNEI <- subset(NEI, fips == "24510" )
SubNEI <-  aggregate(Emissions ~ year * type,data=SubNEI, FUN=sum)
#qplot(log10(Emissions), year, data = SubNEI, facets=.~type, binwith=2,alpha =1/4)
g <- ggplot(SubNEI, aes(log10(Emissions), year, fill = type),is.na = TRUE)
g <- g + geom_point(alpha = 1/3) +geom_bar(stat="identity")+facet_grid(. ~ type) 
print(g)
dev.copy(png, file ="Plot3.png")
dev.off()